### ISSUE TITLE
Generic method with "local" return type will fail to resolve `getExactReturnType`

### ISSUE THREAD

**Issue by leonard84** [coekie/gentyref#5]
Hi,

I encountered the following problem:

Given
```java
public class Parent <A> {
  public <T extends Annotation> T getAnnotation(Class<T> clazz) {
    return null
  }
}

public class Child extends Parent<Child> {
}
```

this call will fail
```java
Method m = Child.getMethod("getAnnotation", Class.class);
GenericTypeReflector.getExactReturnType(m, Child.class);
```

```
UnresolvedTypeVariableException: An exact type is requested, but the type contains a type variable that cannot be resolved.
   Variable: T from public java.lang.annotation.Annotation Parent.getAnnotation(java.lang.Class)
   Hint: This is usually caused by trying to get an exact type when a generic method who's type parameters are not given is involved.
```

The same call does not fail if the containing type is not parameterized.

```java
Method m = Child.getMethod("getAnnotation", Class.class);
GenericTypeReflector.getExactReturnType(m, Class.class);
```

Furthermore, would it be possible to add a `resolveReturnType(Method m, Object[] args)` that could return the actual type for such signatures `<T extends Annotation> T getAnnotation(Class<T> clazz)` when the arguments are given?

**Comment by kaqqao** [comment]
I believe this is intentional, as the _exact_ return type was requested and could not be determined.
In case you care, I maintain [a fork of this project](https://github.com/leangen/geantyref), and added a family of methods that allow incomplete type resolution.
For this specific case, you could use `GenericTypeReflector.getReturnType(m, Class.class)` which would return `T extends Annotation`. From there you could use (the recently added) `reduceBounded` to get `Annotation`.

**Comment by leonard84** [comment]
Hi @kaqqao thanks, I'll have a look at your fork then.

**Comment by coekie** [comment]
Thanks @kaqqao. 
Yes, use the fork. I'm going to archive this repository.
